services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__API_KEY: 1fkYHcY3m3Gjgu9c8Gsogun5zYf069Ldvt2R-lCbfT4
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  indexer:
    build: .
    command: ["python", "main.py", "watch"]
    env_file: .env
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: "6333"
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
    restart: unless-stopped
